### ISSUE TITLE
Problem with coinbase - v2.6.2

### ISSUE THREAD

**Issue by ExEric3** [shiftcurrency/shift#2]
Gshift 2.6.2 havent definied coinbase:

> I0606 09:57:37.684533 p2p/server.go:554] Listening on [::]:53900
> instance: Gshift/v2.6.2/windows/go1.6.2
> coinbase: undefined

Previous version had shiftbase I think.

**Comment by shiftcurrency** [comment]
You must create the coinbase. It is basically an account. So ./gshift
create account

**Comment by shiftcurrency** [comment]
and oh, from version 2.6.2 we have moved from shf to eth, so the coinbase
is defined as eth.coinbase

I see what you mean though, its undefined when you start it. will have a
look.

**Comment by shiftcurrency** [comment]
this is now fixed in the source. thx for the hints up.
